### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by joeyw1030** [Kai-46/ARF-svox2#13]
ERROR: Command errored out with exit status 1:
   command: 'G:\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'H:\\nerf\\ARF-svox2-master1\\ARF-svox2-master\\setup.py'"'"'; __file__='"'"'H:\\nerf\\ARF-svox2-master1\\ARF-svox2-master\\set
up.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp
ile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\dell\AppData\Local\Temp\pip-wheel-6rlrf4nb'
       cwd: H:\nerf\ARF-svox2-master1\ARF-svox2-master\
  Complete output (32 lines):
  H:\nerf\ARF-svox2-master1\ARF-svox2-master\setup.py:25: UserWarning: The environment variable `CUB_HOME` was not found.Installation will fail if your system CUDA toolkit version is less than 11.NVIDIA CUB can be downloaded from `h
ttps://github.com/NVIDIA/cub/releases`. You can unpack it to a location of your choice and set the environment variable `CUB_HOME` to the folder containing the `CMakeListst.txt` file.
    warnings.warn(
  G:\anaconda3\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  running bdist_wheel
  G:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  package init file 'svox2\csrc\__init__.py' not found (or not a regular file)
  running build_ext
  G:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  building 'svox2.csrc' extension
  "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc" -c svox2/csrc/loss_kernel.cu -o build\temp.win-amd64-3.9\Release\svox2/csrc/loss_kernel.obj -IH:\nerf\ARF-svox2-master1\ARF-svox2-master\svox2\csrc\include -IG:\a
naconda3\lib\site-packages\torch\include -IG:\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IG:\anaconda3\lib\site-packages\torch\include\TH -IG:\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\
NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IG:\anaconda3\include -IG:\anaconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Micr
osoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x
86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_confl
ict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4
190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__
CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --use-local-env  
  G:/anaconda3/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
  G:\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(624): error: too few arguments for template template parameter "Tuple"
            detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
  (721): here

  G:\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(717): error: too few arguments for template template parameter "Tuple"
            detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
  (721): here

  2 errors detected in the compilation of "svox2/csrc/loss_kernel.cu".
  loss_kernel.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 1
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "G:\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
  ----------------------------------------
  ERROR: Failed building wheel for svox2
  Running setup.py clean for svox2
Failed to build svox2
Installing collected packages: svox2
    Running setup.py install for svox2 ... error
    ERROR: Command errored out with exit status 1:
     command: 'G:\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'H:\\nerf\\ARF-svox2-master1\\ARF-svox2-master\\setup.py'"'"'; __file__='"'"'H:\\nerf\\ARF-svox2-master1\\ARF-svox2-master\\s
etup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(co
mpile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dell\AppData\Local\Temp\pip-record-q3vs7v9d\install-record.txt' --single-version-externally-managed --compile --install-headers 'G:\anaconda3\Include\svox2'
         cwd: H:\nerf\ARF-svox2-master1\ARF-svox2-master\
    Complete output (47 lines):
    H:\nerf\ARF-svox2-master1\ARF-svox2-master\setup.py:25: UserWarning: The environment variable `CUB_HOME` was not found.Installation will fail if your system CUDA toolkit version is less than 11.NVIDIA CUB can be downloaded from 
`https://github.com/NVIDIA/cub/releases`. You can unpack it to a location of your choice and set the environment variable `CUB_HOME` to the folder containing the `CMakeListst.txt` file.
      warnings.warn(
    G:\anaconda3\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      warnings.warn(
    running install
    G:\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\svox2
    copying svox2\defs.py -> build\lib.win-amd64-3.9\svox2
    copying svox2\setup.py -> build\lib.win-amd64-3.9\svox2
    copying svox2\svox2.py -> build\lib.win-amd64-3.9\svox2
    copying svox2\utils.py -> build\lib.win-amd64-3.9\svox2
    copying svox2\version.py -> build\lib.win-amd64-3.9\svox2
    copying svox2\__init__.py -> build\lib.win-amd64-3.9\svox2
    package init file 'svox2\csrc\__init__.py' not found (or not a regular file)
    running build_ext
    G:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    G:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'svox2.csrc' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\svox2
    creating build\temp.win-amd64-3.9\Release\svox2\csrc
    "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc" -c svox2/csrc/loss_kernel.cu -o build\temp.win-amd64-3.9\Release\svox2/csrc/loss_kernel.obj -IH:\nerf\ARF-svox2-master1\ARF-svox2-master\svox2\csrc\include -IG:
\anaconda3\lib\site-packages\torch\include -IG:\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IG:\anaconda3\lib\site-packages\torch\include\TH -IG:\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program File
s\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IG:\anaconda3\include -IG:\anaconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Mi
crosoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files 
    G:\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(717): error: too few arguments for template template parameter "Tuple"
              detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
    (721): here

    2 errors detected in the compilation of "svox2/csrc/loss_kernel.cu".
    loss_kernel.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 1
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "G:\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'G:\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'H:\\nerf\\ARF-svox2-master1\\ARF-svox2-master\\setup.py'"'"'; __file__='"'"'H:\\nerf\\ARF-s
vox2-master1\\ARF-svox2-master\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"'
, '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dell\AppData\Local\Temp\pip-record-q3vs7v9d\install-record.txt' --single-version-externally-managed --compile --install-headers 'G:\
anaconda3\Include\svox2' Check the logs for full command output.

**Comment by joeyw1030** [comment]
how can i fix it?

**Comment by Kai-46** [comment]
I haven't personally tried the codebase in windows; the codebase was tested on Linux. 

But a quick look at your error log suggests that there might be some issues with pybind11 on windows:

`C:\Program Files
G:\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(717): error: too few arguments for template template parameter "Tuple"`

Maybe you could take a look at it? Here's another thread that might be helpful: https://github.com/facebookresearch/pytorch3d/issues/1024

**Comment by joeyw1030** [comment]
> I haven't personally tried the codebase in windows; the codebase was tested on Linux.
> 
> But a quick look at your error log suggests that there might be some issues with pybind11 on windows:
> 
> `C:\Program Files G:\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(717): error: too few arguments for template template parameter "Tuple"`
> 
> Maybe you could take a look at it? Here's another thread that might be helpful: [facebookresearch/pytorch3d#1024](https://github.com/facebookresearch/pytorch3d/issues/1024)

Now i use 'pip install . --upgrade --use-feature=in-tree-build' already installed svox2.But i run the try_llff.sh will appear:UserWarning: CUDA extension svox2.csrc could not be loaded! Operations will be slow.I found '_C' is None.
