### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by zAuk000** [Kai-46/ARF-svox2#18]
Hi，
when I try to run try{}.sh, it shows no module name sovx2, and I try to run pip install -e . according to https://github.com/sxyu/svox2, but there is an error subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1. could you help me fix it ,Thanks!

**Comment by Kai-46** [comment]
Can you post more detailed error reports?

**Comment by zAuk000** [comment]
. ./try_llff.sh 14
Traceback (most recent call last):
  File "opt.py", line 10, in <module>
    import svox2
ModuleNotFoundError: No module named 'svox2'
Traceback (most recent call last):
  File "opt_style.py", line 9, in <module>
    import svox2
ModuleNotFoundError: No module named 'svox2'
Traceback (most recent call last):
  File "render_imgs.py", line 5, in <module>
    import svox2
ModuleNotFoundError: No module named 'svox2'
